# BUILD
# -----
# Set build configurations for all targets.

[build]
# Additional commands to run prior to building the package.
# These are translated into RUN commands to add to the Docker
# image prior to running cross.
pre-build = [
        "apt-get update && apt-get install --assume-yes libclang1 gcc cmake curl xz-utils clang gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf",
        "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/rust-lang/rust-bindgen/releases/download/v0.70.1/bindgen-cli-installer.sh | sh",
        "mv /root/.cargo/bin/bindgen /usr/bin/bindgen"
]

[target.armv7-unknown-linux-gnueabihf]
image = "ubuntu:22.04"