# Note, this is used in the badge URL!
name: test

on:
  push:
    branches: [dev, master]
    paths:
      [
        "**.rs",
        "Cargo.toml",
        "Cargo.lock",
        "rustfmt.toml",
        ".github/workflows/*",
        "!*.md",
        "!contrib/*",
        "!docs/*",
        "!LICENSE",
        "!*.sh",
      ]
  pull_request:
    paths:
      [
        "**.rs",
        "Cargo.toml",
        "Cargo.lock",
        "rustfmt.toml",
        ".github/workflows/*",
        "!*.md",
        "!contrib/*",
        "!docs/*",
        "!LICENSE",
        "!*.sh",
      ]
  schedule:
    # Run CI every week
    - cron: "00 01 * * 0"

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

# The layering here is as follows:
#  1. code formatting
#  2. absence of lints
#  3. absence of errors and warnings on Linux/x86
#  4. cross compilation on Windows and Linux/ARM

jobs:
  test-cross-arm:
    name: cross +${{ matrix.toolchain }} build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [armv7-unknown-linux-gnueabihf]
        toolchain:
          - "1.77" # MSRV (Minimum supported rust version)
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal --default-toolchain ${{ matrix.toolchain }}  -y
              
      - name: Get Rustc version
        id: get-rustc-version
        run: echo "version=$(rustc -V)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Rust dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-${{ steps.get-rustc-version.outputs.version }}-${{ hashFiles('Cargo.lock') }}
      
      - name: Install the cross compiler targets
        run: rustup target add ${{ matrix.target }}
      
      - name: Install cross compiler toolchain
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf
      
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }} --no-default-features
      
      - name: Check binary
        run: file target/${{ matrix.target }}/debug/librespot
